version: '3.8'

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vocab-backend
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      - FIREBASE_KEY_PATH=/app/serviceAccountKey.json
      - VOSK_MODEL_PATH=/app/model
    volumes:
      - ./backend/serviceAccountKey.json:/app/serviceAccountKey.json
      - ./backend/src/main/resources/model:/app/model
    networks:
      - vocab-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vocab-frontend
    ports:
      - "5173:80"
    depends_on:
      backend:
        condition: service_started
    restart: on-failure
    networks:
      - vocab-network

networks:
  vocab-network:
    driver: bridge

