spring.application.name=vocab
server.port=${PORT:8080}

gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=${GEMINI_API_URL}

nvidia.nim.api.key=${NVIDIA_NIM_API_KEY}
nvidia.nim.model=${MODEL}
anthropic.auth.token=${ANTHROPIC_AUTH_TOKEN}