spring.application.name=vocab
server.port=${PORT:8080}

gemini.api.key=${GEMINI_API_KEY:AIzaSyBgz-0KeK1_VkIl99Jn1UO5zedwB2mXO0k}
gemini.api.url=${GEMINI_API_URL:https://generativelanguage.googleapis.com/v1/models/gemini-1.5-flash:generateContent}
